# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGraphicsView, QLabel, QMainWindow, QPushButton,
    QRadioButton, QSizePolicy, QSlider, QStatusBar,
    QToolButton, QVBoxLayout, QWidget)

from .colorbutton import ColorPickerButton

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1302, 767)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.toolbar_widget = QWidget(self.centralwidget)
        self.toolbar_widget.setObjectName(u"toolbar_widget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar_widget.sizePolicy().hasHeightForWidth())
        self.toolbar_widget.setSizePolicy(sizePolicy)
        self.toolbar_widget.setMinimumSize(QSize(0, 86))
        self.toolbar_widget.setAutoFillBackground(False)
        self.toolbar_widget.setStyleSheet(u"")
        self.frame = QFrame(self.toolbar_widget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(110, 10, 20, 71))
        self.frame.setFrameShape(QFrame.Shape.VLine)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.fog_revealtool_btn = QPushButton(self.toolbar_widget)
        self.fog_revealtool_btn.setObjectName(u"fog_revealtool_btn")
        self.fog_revealtool_btn.setGeometry(QRect(630, 50, 61, 21))
        self.frame_3 = QFrame(self.toolbar_widget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(320, 10, 20, 71))
        self.frame_3.setFrameShape(QFrame.Shape.VLine)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.label_3 = QLabel(self.toolbar_widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(470, 0, 71, 18))
        self.show_playerview_checkBox = QCheckBox(self.toolbar_widget)
        self.show_playerview_checkBox.setObjectName(u"show_playerview_checkBox")
        self.show_playerview_checkBox.setGeometry(QRect(130, 20, 91, 31))
        self.fog_reset_btn = QPushButton(self.toolbar_widget)
        self.fog_reset_btn.setObjectName(u"fog_reset_btn")
        self.fog_reset_btn.setGeometry(QRect(420, 20, 61, 21))
        self.brush_label = QLabel(self.toolbar_widget)
        self.brush_label.setObjectName(u"brush_label")
        self.brush_label.setGeometry(QRect(490, 40, 131, 18))
        self.displaySelect_comboBox = QComboBox(self.toolbar_widget)
        self.displaySelect_comboBox.addItem("")
        self.displaySelect_comboBox.addItem("")
        self.displaySelect_comboBox.setObjectName(u"displaySelect_comboBox")
        self.displaySelect_comboBox.setGeometry(QRect(230, 20, 91, 21))
        self.fog_square_radio = QRadioButton(self.toolbar_widget)
        self.fog_square_radio.setObjectName(u"fog_square_radio")
        self.fog_square_radio.setGeometry(QRect(550, 20, 71, 16))
        self.fog_hidetool_btn = QPushButton(self.toolbar_widget)
        self.fog_hidetool_btn.setObjectName(u"fog_hidetool_btn")
        self.fog_hidetool_btn.setGeometry(QRect(630, 20, 61, 21))
        self.label = QLabel(self.toolbar_widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 0, 41, 18))
        self.fog_circle_radio = QRadioButton(self.toolbar_widget)
        self.fog_circle_radio.setObjectName(u"fog_circle_radio")
        self.fog_circle_radio.setGeometry(QRect(490, 20, 61, 16))
        self.dimensions_btn = QPushButton(self.toolbar_widget)
        self.dimensions_btn.setObjectName(u"dimensions_btn")
        self.dimensions_btn.setGeometry(QRect(230, 50, 91, 21))
        self.fog_enable_checkBox = QCheckBox(self.toolbar_widget)
        self.fog_enable_checkBox.setObjectName(u"fog_enable_checkBox")
        self.fog_enable_checkBox.setGeometry(QRect(340, 20, 91, 21))
        self.label_2 = QLabel(self.toolbar_widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(180, 0, 71, 18))
        self.brush_slider = QSlider(self.toolbar_widget)
        self.brush_slider.setObjectName(u"brush_slider")
        self.brush_slider.setGeometry(QRect(490, 60, 131, 20))
        self.brush_slider.setOrientation(Qt.Orientation.Horizontal)
        self.gmfog_label = QLabel(self.toolbar_widget)
        self.gmfog_label.setObjectName(u"gmfog_label")
        self.gmfog_label.setGeometry(QRect(340, 40, 141, 18))
        self.gmfog_slider = QSlider(self.toolbar_widget)
        self.gmfog_slider.setObjectName(u"gmfog_slider")
        self.gmfog_slider.setGeometry(QRect(340, 60, 141, 20))
        self.gmfog_slider.setOrientation(Qt.Orientation.Horizontal)
        self.web_toolbtn = QToolButton(self.toolbar_widget)
        self.web_toolbtn.setObjectName(u"web_toolbtn")
        self.web_toolbtn.setGeometry(QRect(10, 50, 101, 21))
        self.file_toolbtn = QToolButton(self.toolbar_widget)
        self.file_toolbtn.setObjectName(u"file_toolbtn")
        self.file_toolbtn.setGeometry(QRect(10, 20, 101, 21))
        self.label_4 = QLabel(self.toolbar_widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(930, 0, 31, 18))
        self.lockmap_checkBox = QCheckBox(self.toolbar_widget)
        self.lockmap_checkBox.setObjectName(u"lockmap_checkBox")
        self.lockmap_checkBox.setGeometry(QRect(860, 10, 101, 31))
        self.locktokens_checkBox = QCheckBox(self.toolbar_widget)
        self.locktokens_checkBox.setObjectName(u"locktokens_checkBox")
        self.locktokens_checkBox.setGeometry(QRect(860, 30, 101, 31))
        self.frame_6 = QFrame(self.toolbar_widget)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(690, 10, 20, 71))
        self.frame_6.setFrameShape(QFrame.Shape.VLine)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_7 = QFrame(self.frame_6)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(380, 0, 20, 71))
        self.frame_7.setFrameShape(QFrame.Shape.VLine)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.label_5 = QLabel(self.toolbar_widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(760, 0, 31, 18))
        self.grid_enable_checkBox = QCheckBox(self.toolbar_widget)
        self.grid_enable_checkBox.setObjectName(u"grid_enable_checkBox")
        self.grid_enable_checkBox.setGeometry(QRect(710, 20, 91, 31))
        self.gridcolor_toolbtn = ColorPickerButton(self.toolbar_widget)
        self.gridcolor_toolbtn.setObjectName(u"gridcolor_toolbtn")
        self.gridcolor_toolbtn.setGeometry(QRect(710, 50, 61, 21))
        self.frame_8 = QFrame(self.toolbar_widget)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(840, 10, 20, 71))
        self.frame_8.setFrameShape(QFrame.Shape.VLine)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_9 = QFrame(self.frame_8)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(380, 0, 20, 71))
        self.frame_9.setFrameShape(QFrame.Shape.VLine)
        self.frame_9.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_10 = QFrame(self.frame_8)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(20, 0, 20, 71))
        self.frame_10.setFrameShape(QFrame.Shape.VLine)
        self.frame_10.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_11 = QFrame(self.frame_10)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(380, 0, 20, 71))
        self.frame_11.setFrameShape(QFrame.Shape.VLine)
        self.frame_11.setFrameShadow(QFrame.Shadow.Raised)
        self.gridabove_checkBox = QCheckBox(self.toolbar_widget)
        self.gridabove_checkBox.setObjectName(u"gridabove_checkBox")
        self.gridabove_checkBox.setGeometry(QRect(780, 20, 71, 31))
        self.gridcolor_reset_toolbtn = QToolButton(self.toolbar_widget)
        self.gridcolor_reset_toolbtn.setObjectName(u"gridcolor_reset_toolbtn")
        self.gridcolor_reset_toolbtn.setGeometry(QRect(780, 50, 61, 21))
        self.zoom_label = QLabel(self.toolbar_widget)
        self.zoom_label.setObjectName(u"zoom_label")
        self.zoom_label.setGeometry(QRect(860, 60, 41, 16))
        self.zoom_slider = QSlider(self.toolbar_widget)
        self.zoom_slider.setObjectName(u"zoom_slider")
        self.zoom_slider.setGeometry(QRect(900, 60, 131, 20))
        self.zoom_slider.setOrientation(Qt.Orientation.Horizontal)
        self.frame_12 = QFrame(self.toolbar_widget)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(1030, 10, 20, 71))
        self.frame_12.setFrameShape(QFrame.Shape.VLine)
        self.frame_12.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_13 = QFrame(self.frame_12)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(380, 0, 20, 71))
        self.frame_13.setFrameShape(QFrame.Shape.VLine)
        self.frame_13.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_14 = QFrame(self.frame_12)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(20, 0, 20, 71))
        self.frame_14.setFrameShape(QFrame.Shape.VLine)
        self.frame_14.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_15 = QFrame(self.frame_14)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(380, 0, 20, 71))
        self.frame_15.setFrameShape(QFrame.Shape.VLine)
        self.frame_15.setFrameShadow(QFrame.Shadow.Raised)
        self.bgcolor_toolbtn = ColorPickerButton(self.toolbar_widget)
        self.bgcolor_toolbtn.setObjectName(u"bgcolor_toolbtn")
        self.bgcolor_toolbtn.setGeometry(QRect(970, 20, 61, 21))
        self.bgcolor_reset_toolbtn = QToolButton(self.toolbar_widget)
        self.bgcolor_reset_toolbtn.setObjectName(u"bgcolor_reset_toolbtn")
        self.bgcolor_reset_toolbtn.setGeometry(QRect(970, 40, 61, 21))
        self.label_6 = QLabel(self.toolbar_widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1110, 0, 71, 18))
        self.placeParty_btn = QToolButton(self.toolbar_widget)
        self.placeParty_btn.setObjectName(u"placeParty_btn")
        self.placeParty_btn.setGeometry(QRect(1050, 20, 91, 21))
        self.removeParty_btn = QToolButton(self.toolbar_widget)
        self.removeParty_btn.setObjectName(u"removeParty_btn")
        self.removeParty_btn.setGeometry(QRect(1150, 20, 91, 21))
        self.clearParty_btn = QToolButton(self.toolbar_widget)
        self.clearParty_btn.setObjectName(u"clearParty_btn")
        self.clearParty_btn.setGeometry(QRect(1180, 50, 61, 21))
        self.partyMembers_comboBox = QComboBox(self.toolbar_widget)
        self.partyMembers_comboBox.setObjectName(u"partyMembers_comboBox")
        self.partyMembers_comboBox.setGeometry(QRect(1050, 50, 121, 21))
        self.frame_16 = QFrame(self.toolbar_widget)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setGeometry(QRect(1240, 10, 20, 71))
        self.frame_16.setFrameShape(QFrame.Shape.VLine)
        self.frame_16.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_17 = QFrame(self.frame_16)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setGeometry(QRect(380, 0, 20, 71))
        self.frame_17.setFrameShape(QFrame.Shape.VLine)
        self.frame_17.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_18 = QFrame(self.frame_16)
        self.frame_18.setObjectName(u"frame_18")
        self.frame_18.setGeometry(QRect(20, 0, 20, 71))
        self.frame_18.setFrameShape(QFrame.Shape.VLine)
        self.frame_18.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_19 = QFrame(self.frame_18)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setGeometry(QRect(380, 0, 20, 71))
        self.frame_19.setFrameShape(QFrame.Shape.VLine)
        self.frame_19.setFrameShadow(QFrame.Shadow.Raised)
        self.hide_playerview_checkBox = QCheckBox(self.toolbar_widget)
        self.hide_playerview_checkBox.setObjectName(u"hide_playerview_checkBox")
        self.hide_playerview_checkBox.setGeometry(QRect(130, 40, 91, 31))

        self.verticalLayout_2.addWidget(self.toolbar_widget)

        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")

        self.verticalLayout_2.addWidget(self.graphicsView)

        self.verticalLayout_2.setStretch(1, 1)

        self.verticalLayout.addLayout(self.verticalLayout_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.fog_revealtool_btn.setText(QCoreApplication.translate("MainWindow", u"Reveal", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Fog of War", None))
        self.show_playerview_checkBox.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.fog_reset_btn.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.brush_label.setText(QCoreApplication.translate("MainWindow", u"Brush Size", None))
        self.displaySelect_comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Display 1", None))
        self.displaySelect_comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Display 2", None))

        self.fog_square_radio.setText(QCoreApplication.translate("MainWindow", u"Square", None))
        self.fog_hidetool_btn.setText(QCoreApplication.translate("MainWindow", u"Hide", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.fog_circle_radio.setText(QCoreApplication.translate("MainWindow", u"Circle", None))
        self.dimensions_btn.setText(QCoreApplication.translate("MainWindow", u"Dimensions", None))
        self.fog_enable_checkBox.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Player View", None))
        self.gmfog_label.setText(QCoreApplication.translate("MainWindow", u"GM Fog Opacity", None))
        self.web_toolbtn.setText(QCoreApplication.translate("MainWindow", u"Player Share", None))
        self.file_toolbtn.setText(QCoreApplication.translate("MainWindow", u"File ...", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Map", None))
        self.lockmap_checkBox.setText(QCoreApplication.translate("MainWindow", u"Lock Assets", None))
        self.locktokens_checkBox.setText(QCoreApplication.translate("MainWindow", u"Lock Tokens", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Grid", None))
        self.grid_enable_checkBox.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.gridcolor_toolbtn.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.gridabove_checkBox.setText(QCoreApplication.translate("MainWindow", u"Above", None))
        self.gridcolor_reset_toolbtn.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.zoom_label.setText(QCoreApplication.translate("MainWindow", u"Zoom", None))
        self.bgcolor_toolbtn.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.bgcolor_reset_toolbtn.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Party Tokens", None))
        self.placeParty_btn.setText(QCoreApplication.translate("MainWindow", u"Summon", None))
        self.removeParty_btn.setText(QCoreApplication.translate("MainWindow", u"Dismiss", None))
        self.clearParty_btn.setText(QCoreApplication.translate("MainWindow", u"Disband", None))
        self.hide_playerview_checkBox.setText(QCoreApplication.translate("MainWindow", u"Hide Map", None))
    # retranslateUi

